# Generated by Django 2.1.2 on 2018-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1500)),
                ('email', models.EmailField(max_length=200)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
