# Generated by Django 2.1.2 on 2018-10-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
    ]
