# Generated by Django 2.1.2 on 2018-10-22 06:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0003_auto_20181018_0718'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
