# Generated by Django 2.1.2 on 2018-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0004_auto_20181022_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
    ]
